spring:
  application:
    name: sisprot
  datasource:
    url: jdbc:postgresql://localhost:5432/sisprot
    username: sisprot
    password: sisprot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
